// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// VITE_ vars são públicas (anon/publishable) mas vêm do ambiente (Vercel/Supabase).
// Não há fallback hard-coded para evitar expor project_id/chave no Git.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("[supabase] VITE_SUPABASE_URL ou VITE_SUPABASE_PUBLISHABLE_KEY em falta - verifica .env / Vercel env");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});